// Operation-type guidelines module
function buildOperationGuidelines() {
  return [
    "",
    "========================================",
    "OPERATION GUIDELINES",
    "========================================",
    "You MUST use TWO types of code blocks for different operations:",
    "- ```sr blocks = ONLY for file content editing (SEARCH/REPLACE)",
    "- ```op blocks = ONLY for file system operations (create directory, move, delete)",
    "",
    "========================================",
    "EXAMPLE 1: SEARCH/REPLACE for content editing",
    "========================================",
    "```sr",
    "FILE: app.js",
    "SEARCH:",
    "<<<",
    "const calculator = require('./calculator');",
    ">>>",
    "REPLACE:",
    "<<<",
    "const calculator = require('./lib/calculator');",
    ">>>",
    "```",
    "",
    "========================================",
    "EXAMPLE 2: File operations",
    "========================================",
    "",
    "To create a directory:",
    "```op",
    "MKDIR: lib",
    "```",
    "",
    "To move/rename a file:",
    "```op",
    "MV: calculator.js -> lib/calculator.js",
    "```",
    "",
    "To delete a file:",
    "```op",
    "RM: old-file.js",
    "```",
    "",
    "========================================",
    "DETAILED RULES",
    "=======================================",
    "- For content editing: use ONLY ```sr blocks",
    "- For creating a directory: use ONLY ```op with MKDIR",
    "- For moving a file: use ONLY ```op with MV",
    "- For deleting a file: use ONLY ```op with RM",
    "- If SEARCH is non-empty, it MUST match exactly once in the current file",
    "- If SEARCH is empty, overwrite the whole file with REPLACE (create if missing)",
    "- When creating a new file, always set SEARCH to empty string",
    "- MV automatically creates parent directories - no need to MKDIR first",
    "- DO NOT create a file named `lib` when you want a directory called `lib`",
    "- DO NOT use SEARCH/REPLACE to delete files - use RM instead",
    "- DO NOT manually copy content then delete original - use MV",
    "- When updating require/import paths, use paths relative to the file being edited",
    "- Output ONLY the blocks - no extra text, explanations, or separators",
    "- IMPORTANT: sr block content must NOT contain >>> anywhere - use --- instead of >>> for separators"
  ].join("\n");
}

module.exports = {
  buildOperationGuidelines
};