// Output discipline module
function buildOutputDiscipline() {
  return [
    "",
    "========================================",
    "OUTPUT DISCIPLINE",
    "========================================",
    "1. FORMAT REQUIREMENTS:",
    "   - PREFERRED: Output valid JSON with tool_calls array (see examples below)",
    "   - ALTERNATIVE: Output ```sr or ```op blocks if JSON is not feasible",
    "   - No extra prose, explanations, or comments outside JSON/sr/op blocks",
    "   - No git patches or unified diffs",
    "   - Use proper indentation and formatting",
    "",
    "2. JSON FORMAT (PREFERRED):",
    "   - Output a single valid JSON object",
    "   - Structure: { \"tool_calls\": [{ \"function\": { \"name\": \"...\", \"arguments\": {...} } }] }",
    "   - arguments must be an object (not a string)",
    "   - File paths must be relative to workspace (no absolute paths)",
    "",
    "3. VALIDATION STANDARDS:",
    "   - All changes must be syntactically correct",
    "   - All paths must be valid and within the workspace",
    "   - All SEARCH patterns must match existing content exactly (when non-empty)",
    "   - All operations must be safe and reversible",
    "",
    "4. DENIED OPERATIONS:",
    "   - bash, npm, git, shell, exec, run, command - these are blocked",
    "   - Only file operations (search_replace, mkdir, mv, rm) are allowed",
    "   - Absolute paths are not allowed - use relative paths within workspace",
    "",
    "5. COMPLETION CRITERIA:",
    "   - Code changes successfully applied",
    "   - Syntax and semantic validation passed",
    "   - No unresolved errors or warnings",
    "   - All engineering constraints satisfied",
    "",
    "6. EXAMPLES:",
    "",
    "   Example 1 - JSON format (PREFERRED):",
    "   {",
    "     \"tool_calls\": [",
    "       {",
    "         \"function\": {",
    "           \"name\": \"search_replace\",",
    "           \"arguments\": {",
    "             \"file\": \"src/utils.js\",",
    "             \"search\": \"const add = (a, b) => a + b;\",",
    "             \"replace\": \"const add = (a, b) => {\\n  return a + b;\\n};\",",
    "           }",
    "         }",
    "       }",
    "     ]",
    "   }",
    "",
    "   Example 2 - JSON format with mkdir:",
    "   {",
    "     \"tool_calls\": [",
    "       {",
    "         \"function\": {",
    "           \"name\": \"mkdir\",",
    "           \"arguments\": { \"path\": \"src/newdir\" }",
    "         }",
    "       }",
    "     ]",
    "   }",
    "",
    "   Example 3 - SEARCH/REPLACE (sr) - ALTERNATIVE:",
    "   ```sr",
    "   FILE: src/utils.js",
    "   SEARCH:",
    "   <<<",
    "   const add = (a, b) => a + b;",
    "   >>>",
    "   REPLACE:",
    "   <<<",
    "   const add = (a, b) => {",
    "     return a + b;",
    "   };",
    "   >>>",
    "   ```",
    "",
    "   Example 4 - OPERATION (op) - MKDIR:",
    "   ```op",
    "   MKDIR: src/newdir",
    "   ```",
    "",
    "   Example 5 - OPERATION (op) - MV:",
    "   ```op",
    "   MV: src/old.js -> src/new.js",
    "   ```",
    "",
    "   Example 6 - OPERATION (op) - RM:",
    "   ```op",
    "   RM: src/unused.js",
    "   ```"
  ].join("\n");
}

module.exports = {
  buildOutputDiscipline
};