// Output discipline module
function buildOutputDiscipline() {
  return [
    "",
    "========================================",
    "OUTPUT DISCIPLINE",
    "========================================",
    "1. FORMAT REQUIREMENTS:",
    "   - Output ONLY ```sr or ```op blocks",
    "   - No extra prose, explanations, or comments",
    "   - No git patches or unified diffs",
    "   - Use proper indentation and formatting",
    "",
    "2. VALIDATION STANDARDS:",
    "   - All changes must be syntactically correct",
    "   - All paths must be valid and within the workspace",
    "   - All SEARCH patterns must match existing content exactly (when non-empty)",
    "   - All operations must be safe and reversible",
    "",
    "3. DENIED OPERATIONS:",
    "   - bash, npm, git, shell, exec, run, command - these are blocked",
    "   - Only file operations (search_replace, mkdir, mv, rm) are allowed",
    "   - Absolute paths are not allowed - use relative paths within workspace",
    "",
    "4. COMPLETION CRITERIA:",
    "   - Code changes successfully applied",
    "   - Syntax and semantic validation passed",
    "   - No unresolved errors or warnings",
    "   - All engineering constraints satisfied",
    "",
    "5. EXAMPLES:",
    "",
    "   Example 1 - SEARCH/REPLACE (sr):",
    "   ```sr",
    "   FILE: src/utils.js",
    "   SEARCH:",
    "   <<<",
    "   const add = (a, b) => a + b;",
    "   >>>",
    "   REPLACE:",
    "   <<<",
    "   const add = (a, b) => {",
    "     return a + b;",
    "   };",
    "   >>>",
    "   ```",
    "",
    "   Example 2 - OPERATION (op) - MKDIR:",
    "   ```op",
    "   MKDIR: src/newdir",
    "   ```",
    "",
    "   Example 3 - OPERATION (op) - MV:",
    "   ```op",
    "   MV: src/old.js -> src/new.js",
    "   ```",
    "",
    "   Example 4 - OPERATION (op) - RM:",
    "   ```op",
    "   RM: src/unused.js",
    "   ```"
  ].join("\n");
}

module.exports = {
  buildOutputDiscipline
};